FROM docker.io/nvidia/cuda:11.4.3-cudnn8-runtime-ubuntu20.04

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractiv apt-get install -y --no-install-recommends \
    python3-pip \
    python3-tk \
    vim  \
    wget \
    curl \
    nodejs \
    npm \
    procps \
    git  && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install        \
    decorator==5.1.1    \
    ipykernel==6.16.2   \
    ipython==8.5.0      \
    jupyterlab==3.5.0   \
    matplotlib==3.5.3   \
    jupyterlab-widgets  \
    jupyter_contrib_nbextensions \
    seaborn==0.12.1     \
    numpy==1.23.4       \
    pandas==1.5.1       \
    scipy==1.9.3        \
    scikit-learn==1.3.0 \
    protobuf==3.19.6    \
    opencv-python==4.6.0.66 \
    segyio \
    Pillow==8.3.0                 \
    jsonschema \
    jsonpointer>1.13 \
    webcolors>=1.11  \
    isoduration \
    uri-template \
    fqdn \
    tqdn \
    pyyaml 



